name: Build Strom

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout code
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build meson g++ libboost-program-options-dev libboost-filesystem-dev libncl-dev
          
    - name: Create build directory
      run: cd src && meson setup builddir
      
    - name: Compile project
      run: meson compile -C builddir
      
    - name: Install project
      run: meson install -C buildir
